apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sistema-control
type: Opaque
stringData:
  POSTGRES_DB: CAMBIAR_DB
  POSTGRES_USER: CAMBIAR_USUARIO
  POSTGRES_PASSWORD: CAMBIAR_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sistema-control
type: Opaque
stringData:
  DB_NAME: CAMBIAR_DB
  DB_USER: CAMBIAR_USUARIO
  DB_PASSWORD: CAMBIAR_PASSWORD
  JWT_SECRET: CAMBIAR_JWT_SECRET
  JWT_EXPIRES_IN: "8h"