apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sistema-control
type: Opaque
stringData:
  POSTGRES_DB: guaracadaqui_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Keyla2022

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sistema-control
type: Opaque
stringData:
  DB_NAME: guaracadaqui_db
  DB_USER: postgres
  DB_PASSWORD: Keyla2022

  JWT_SECRET: super_secret_key_123
  JWT_EXPIRES_IN: "8h"