apiVersion: v1
kind: ServiceAccount
metadata:
  name: sistema-control-sa
  namespace: sistema-control

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sistema-control-role
  namespace: sistema-control
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sistema-control-rolebinding
  namespace: sistema-control
subjects:
  - kind: ServiceAccount
    name: sistema-control-sa
    namespace: sistema-control
roleRef:
  kind: Role
  name: sistema-control-role
  apiGroup: rbac.authorization.k8s.io